const PastCareActionTypes = {
  SET_DATA: "CALENDAR/SET_DATA",
  FIND_REMINDERS: "CALENDAR/FIND_REMINDERS",
  ADD_NEW_EVENT: "CALENDAR/ADD_NEW_EVENT",
  ADD_TO_LOCAL_STORAGE: "CALENDAR/ADD_TO_LOCAL_STORAGE"
};

export default PastCareActionTypes;
